// Generated by CoffeeScript 1.6.3
var HttpRequest, deferred, testable;

deferred = require('../support').deferred;

HttpRequest = require('./http_request');

testable = void 0;

exports._authenticator = function() {
  return testable;
};

exports.Authenticator = function(config, queue) {
  var api, authenticator;
  config || (config = {});
  authenticator = {
    queue: queue,
    authenticating: 0,
    configured: function() {
      return config.authenticator != null;
    },
    authenticate: deferred(function(action, httpRequest) {
      var error;
      if (!authenticator.configured()) {
        error = new Error('dinkum absence of authenticator config');
        error.detail = httpRequest.opts;
        httpRequest.promised.reject(error);
        action.reject();
        return;
      }
      authenticator.authenticating = httpRequest.sequence;
      return action.resolve(new HttpRequest);
    })
  };
  testable = authenticator;
  return api = {
    authenticate: authenticator.authenticate
  };
};
