// Generated by CoffeeScript 1.6.3
var deferred, testable;

deferred = require('../support').deferred;

testable = void 0;

exports._authenticator = function() {
  return testable;
};

exports.Authenticator = function(config, queue) {
  var api, authenticator;
  authenticator = {
    queue: queue,
    authenticating: false,
    authenticate: function() {
      return authenticator.authenticating = true;
    }
  };
  testable = authenticator;
  return api = {
    authenticate: authenticator.authenticate
  };
};
