// Generated by CoffeeScript 1.6.3
var CookieStore, defer, https;

https = require('https');

defer = require('when').defer;

CookieStore = require('./cookie_store');

exports.create = function(config) {
  var cookies, session;
  if (!((config != null) && (config.username != null) && (config.password != null) && (config.hostname != null))) {
    throw new Error('BasicAuth.create(config) requires config.username, config.password, config.hostname');
  }
  cookies = CookieStore.create(config);
  config.port || (config.port = 443);
  return session = {
    get: function(opts, deferral) {
      var request;
      if (opts == null) {
        opts = {};
      }
      if (deferral == null) {
        deferral = defer();
      }
      opts.method = 'GET';
      opts.path = '/';
      request = https.request({
        hostname: config.hostname,
        port: config.port,
        path: opts.path,
        method: opts.method,
        headers: {
          cookie: cookies.getCookie()
        }
      });
      return deferral.promise;
    }
  };
};
