// Generated by CoffeeScript 1.6.3
var client, defer, enclose, requestor;

enclose = require('../support').enclose;

defer = require('when').defer;

requestor = require('./requestor').requestor;

client = void 0;

exports.testable = function() {
  return client;
};

exports.client = enclose(requestor, function(superclass, config) {
  var api;
  client = {
    superclass: superclass,
    get: function(opts, result) {
      if (result == null) {
        result = defer();
      }
      opts.method = 'GET';
      superclass.request(opts, result).then(function() {}, result.error, result.notify);
      return result.promise;
    }
  };
  return api = {
    get: client.get
  };
});
