// Generated by CoffeeScript 1.6.3
var Requestor, client, defer, deferred, enclose, _ref;

_ref = require('../support'), enclose = _ref.enclose, deferred = _ref.deferred;

defer = require('when').defer;

Requestor = require('./requestor').Requestor;

client = void 0;

exports.testable = function() {
  return client;
};

exports.client = enclose(Requestor, function(requestor, config) {
  var api;
  client = {
    requestor: requestor,
    get: function(opts, result) {
      if (result == null) {
        result = defer();
      }
      opts.method = 'GET';
      requestor.request(opts, result).then(function() {}, result.error, result.notify);
      return result.promise;
    },
    stats: deferred(function(action) {
      var notify, reject, resolve;
      resolve = action.resolve, reject = action.reject, notify = action.notify;
      return superclass.stats().then(resolve, reject, notify);
    })
  };
  return api = {
    get: client.get,
    stats: client.stats
  };
});
