// Generated by CoffeeScript 1.6.3
exports.create = function(config) {
  var store;
  if (config.hostname == null) {
    throw new Error('CookieStore.create(config) requires config.hostname');
  }
  store = [];
  return {
    setCookie: function(cookies) {
      return store = cookies;
    },
    getCookie: function() {
      if (!(store.length > 0)) {
        return;
      }
      return store.map(function(cookie) {
        try {
          return cookie.match(/(.*?);/)[1];
        } catch (_error) {}
      }).join('; ') + ';';
    }
  };
};
