// Generated by CoffeeScript 1.6.3
exports.create = function(config) {
  var store;
  if (config.hostname == null) {
    throw new Error('CookieStore.create(config) requires config.hostname');
  }
  return store = {
    cookies: {},
    setCookie: function(cookies) {
      var cookie, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = cookies.length; _i < _len; _i++) {
        cookie = cookies[_i];
        _results.push(store.cookies[cookie] = Date.now());
      }
      return _results;
    },
    getCookie: function() {
      var cookie, cookieString, pair;
      cookieString = '';
      for (cookie in store.cookies) {
        try {
          pair = cookie.match(/(.*?);/)[1];
          cookieString += pair + '; ';
        } catch (_error) {}
      }
      if (!cookieString) {
        return void 0;
      }
      return cookieString.slice(0, -1);
    }
  };
};
