// Generated by CoffeeScript 1.6.3
var HttpReuquest;

module.exports = HttpReuquest = (function() {
  function HttpReuquest(deferral, opts) {
    var sequence;
    this.deferral = deferral;
    this.opts = opts;
    sequence = void 0;
    Object.defineProperty(this, 'sequence', {
      enumerable: true,
      get: function() {
        return sequence;
      },
      set: function(value) {
        if (sequence != null) {
          return;
        }
        if (typeof value !== 'number') {
          return;
        }
        return sequence = value;
      }
    });
  }

  return HttpReuquest;

})();
