// Generated by CoffeeScript 1.6.3
var HttpReuquest;

module.exports = HttpReuquest = (function() {
  function HttpReuquest(promised, opts) {
    var sequence, state;
    this.promised = promised;
    this.opts = opts;
    sequence = void 0;
    state = {
      value: 'pending'
    };
    Object.defineProperty(this, 'sequence', {
      enumerable: true,
      get: function() {
        return sequence;
      },
      set: function(value) {
        if (sequence != null) {
          return;
        }
        if (typeof value !== 'number') {
          return;
        }
        return sequence = value;
      }
    });
    Object.defineProperty(this, 'state', {
      enumerable: true,
      get: function() {
        return state.value;
      }
    });
  }

  return HttpReuquest;

})();
