// Generated by CoffeeScript 1.6.3
var HttpReuquest;

module.exports = HttpReuquest = (function() {
  function HttpReuquest(promised, opts) {
    var local, onDone, sequence,
      _this = this;
    this.promised = promised;
    this.opts = opts;
    this.error = void 0;
    sequence = void 0;
    onDone = void 0;
    local = {
      state: {
        value: 'pending',
        at: Date.now()
      }
    };
    Object.defineProperty(this, 'sequence', {
      enumerable: true,
      get: function() {
        return sequence;
      },
      set: function(value) {
        if (sequence != null) {
          return;
        }
        if (typeof value !== 'number') {
          return;
        }
        return sequence = value;
      }
    });
    Object.defineProperty(this, 'state', {
      enumerable: true,
      get: function() {
        return local.state.value;
      },
      set: function(value) {
        local.state.value = value;
        local.state.at = Date.now();
        switch (value) {
          case 'done':
            return onDone(_this.error, _this);
        }
      }
    });
    Object.defineProperty(this, 'stateAt', {
      enumerable: true,
      get: function() {
        return local.state.at;
      }
    });
    Object.defineProperty(this, 'onDone', {
      enumerable: false,
      set: function(fn) {
        if (onDone != null) {
          return;
        }
        if (typeof fn !== 'function') {
          return;
        }
        return onDone = fn;
      }
    });
  }

  return HttpReuquest;

})();
