// Generated by CoffeeScript 1.6.3
var extend, queue;

extend = require('../support').extend;

queue = void 0;

exports.testable = function() {
  return queue;
};

exports.create = function(config) {
  var api;
  queue = {
    sequence: 0,
    queued: {},
    enqueue: function(object) {
      return queue.queued[(++queue.sequence).toString()] = {
        object: object
      };
    }
  };
  return api = {
    enqueue: queue.enqueue
  };
};
