// Generated by CoffeeScript 1.6.3
var extend, promised, queue, requestor, _ref;

_ref = require('../support'), extend = _ref.extend, promised = _ref.promised;

queue = require('./queue').queue;

requestor = void 0;

exports.testable = function() {
  return requestor;
};

exports.requestor = extend(queue, function(superclass, config) {
  var api;
  if (config == null) {
    config = {};
  }
  config.transport || (config.transport = 'https');
  requestor = {
    superclass: superclass,
    request: promised(function(action) {
      return superclass.enqueue().then(function() {
        return action.resolve();
      });
    })
  };
  return api = {
    request: requestor.request
  };
});
