// Generated by CoffeeScript 1.6.3
var HttpRequest, Queue, Transport, count, deferred, enclose, parallel, requestor, sequence, _ref;

_ref = require('../support'), enclose = _ref.enclose, deferred = _ref.deferred;

Queue = require('./queue').Queue;

Transport = require('./transport').Transport;

HttpRequest = require('./http_request');

sequence = require('when/sequence');

parallel = require('when/parallel');

count = 0;

requestor = void 0;

exports.testable = function() {
  return requestor;
};

exports.Requestor = enclose(Queue, function(queue, config) {
  var api;
  if (config == null) {
    config = {};
  }
  requestor = {
    queue: queue,
    transport: Transport(config, queue),
    request: deferred(function(action, opts, promised) {
      var newRequest, notify, reject, resolve;
      resolve = action.resolve, reject = action.reject, notify = action.notify;
      newRequest = new HttpRequest(promised, opts);
      newRequest.onDone = requestor.done;
      return sequence([
        function() {
          return queue.enqueue(newRequest);
        }, function() {
          return queue.dequeue();
        }
      ]).then(function(_arg) {
        var NULL, httpRequest, requests;
        NULL = _arg[0], requests = _arg[1];
        return parallel((function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = requests.length; _i < _len; _i++) {
            httpRequest = requests[_i];
            _results.push((function(httpRequest) {
              return function() {
                return requestor.transport.request(httpRequest);
              };
            })(httpRequest));
          }
          return _results;
        })()).then(resolve, reject, notify);
      }, reject, notify);
    }),
    done: deferred(function(action, error, httpRequest) {
      var notify, reject, resolve;
      resolve = action.resolve, reject = action.reject, notify = action.notify;
      return sequence([
        function() {
          return queue.done(error, httpRequest);
        }, function() {
          return queue.dequeue();
        }
      ]).then(function(_arg) {
        var NULL, requests;
        NULL = _arg[0], requests = _arg[1];
        return parallel((function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = requests.length; _i < _len; _i++) {
            httpRequest = requests[_i];
            _results.push((function(httpRequest) {
              return function() {
                return requestor.transport.request(httpRequest);
              };
            })(httpRequest));
          }
          return _results;
        })()).then(resolve, reject, notify);
      }, reject, notify);
    }),
    stats: deferred(function(action) {
      var notify, reject, resolve;
      resolve = action.resolve, reject = action.reject, notify = action.notify;
      return queue.stats().then(resolve, reject, notify);
    })
  };
  return api = {
    request: requestor.request,
    stats: requestor.stats
  };
});
