// Generated by CoffeeScript 1.6.3
var promised, transport;

promised = require('../support').promised;

transport = void 0;

exports.testable = function() {
  return transport;
};

exports.transport = function(config) {
  var api;
  if (config == null) {
    config = {};
  }
  transport = {
    request: promised(function(action, opts, result) {
      if (opts == null) {
        opts = {};
      }
      return require(config.transport).request(opts);
    })
  };
  return api = {
    request: transport.request
  };
};
