// Generated by CoffeeScript 1.6.3
var defer,
  __slice = [].slice;

defer = require('when').defer;

module.exports = function(fn) {
  return function() {
    var args, promised;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    promised = defer();
    fn.apply(this, [promised].concat(args));
    return promised.promise;
  };
};
