// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

module.exports = function(superFn, fn) {
  return function() {
    var args, object, superclass;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    superclass = typeof superFn !== 'function' ? superFn : superFn.apply(this, args);
    object = fn.apply(this, [superclass].concat(args));
    return object;
  };
};
