// Generated by CoffeeScript 1.6.3
module.exports = function(superFn, fn) {
  var object, property;
  if (fn == null) {
    fn = {};
  }
  if (typeof fn !== 'function') {
    object = fn;
    for (property in superFn) {
      object[property] || (object[property] = superFn[property]);
    }
    return object;
  }
  return function() {
    var superclass;
    superclass = typeof superFn !== 'function' ? superFn : superFn.apply(this, arguments);
    superclass || (superclass = {});
    object = fn.apply(this, arguments);
    object || (object = {});
    for (property in superclass) {
      object[property] || (object[property] = superclass[property]);
    }
    return object;
  };
};
