// Generated by CoffeeScript 1.6.3
module.exports = function(superFn, fn) {
  var property;
  if (fn == null) {
    fn = function() {};
  }
  for (property in superFn) {
    fn[property] || (fn[property] = superFn[property]);
  }
  return fn;
};
