// Generated by CoffeeScript 1.6.3
var defaultFilters,
  __slice = [].slice;

defaultFilters = {
  'application/json': function(opts) {
    var encoded;
    encoded = JSON.stringify(opts['application/json']);
    opts.headers || (opts.headers = {});
    opts.headers['content-type'] = 'application/json';
    return opts.body = encoded;
  }
};

module.exports = function(config, fn) {
  var localFilters, type;
  localFilters = defaultFilters;
  for (type in config.content) {
    if (config.content[type].encode != null) {
      localFilters[type] = config.content[type].encode;
    }
  }
  return function() {
    var contentType, more, opts;
    opts = arguments[0], more = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (opts['application/json'] != null) {
      localFilters['application/json'](opts);
    } else {
      for (contentType in localFilters) {
        if (opts[contentType] != null) {
          localFilters[contentType](opts);
          break;
        }
      }
    }
    return fn.apply(this, arguments);
  };
};

module.exports.filters = defaultFilters;
