// Generated by CoffeeScript 1.6.3
var defaultFilters,
  __slice = [].slice;

defaultFilters = {
  json: function(opts) {
    var encoded;
    encoded = JSON.stringify(opts.json);
    opts.headers || (opts.headers = {});
    opts.headers['content-length'] = encoded.length;
    opts.headers['content-type'] = 'application/json';
    return opts.body = encoded;
  }
};

module.exports = function(config, fn) {
  var localFilters, type;
  localFilters = defaultFilters;
  for (type in config.content) {
    if (config.content[type].encode != null) {
      localFilters[type] = config.content[type].encode;
    }
  }
  return function() {
    var more, opts;
    opts = arguments[0], more = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (opts.json != null) {
      localFilters.json(opts);
    }
    return fn.apply(this, arguments);
  };
};

module.exports.filters = defaultFilters;
