// Generated by CoffeeScript 1.6.3
var defaultFilters,
  __slice = [].slice;

defaultFilters = {
  json: function(opts) {
    return console.log({
      WITH_JSON: opts
    });
  }
};

module.exports = function(config, fn) {
  var localFilters, type;
  localFilters = defaultFilters;
  for (type in config.content) {
    localFilters[type] = config.content[type];
  }
  return function() {
    var more, opts;
    opts = arguments[0], more = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (opts.json != null) {
      localFilters.json(opts);
    }
    return fn.apply(this, arguments);
  };
};

module.exports.filters = defaultFilters;
