// Generated by CoffeeScript 1.6.3
var defaultFilters;

defaultFilters = {
  'application/json': function(httpResult) {
    var decoded;
    decoded = JSON.parse(httpResult.body);
    return httpResult.body = decoded;
  }
};

module.exports = function(config) {
  var localFilters, type;
  localFilters = defaultFilters;
  for (type in config.content) {
    if (config.content[type].decode != null) {
      localFilters[type] = config.content[type].decode;
    }
  }
  return function(httpResult) {
    var contentType, contentTypeHeader;
    try {
      contentTypeHeader = contentType = httpResult.headers['content-type'];
    } catch (_error) {}
    if (contentTypeHeader != null) {
      try {
        contentType = contentTypeHeader.match(/(.*?);/)[1];
      } catch (_error) {}
      if (localFilters[contentType] != null) {
        return localFilters[contentType](httpResult);
      }
    }
  };
};
