// Generated by CoffeeScript 1.6.3
var Client;

Client = require('./client/client').Client;

exports.Client = {
  create: function(config) {
    if (config == null) {
      config = {};
    }
    config.transport || (config.transport = 'https');
    config.hostname || (config.hostname = 'localhost');
    if (config.queueLimit == null) {
      config.queueLimit = 100;
    }
    if (config.requestLimit == null) {
      config.requestLimit = 10;
    }
    config.connectTimeout || (config.connectTimeout = 0);
    if (config.allowUncertified == null) {
      config.allowUncertified = false;
    }
    return Client(config);
  }
};

exports.Test = require('./test');
