// Generated by CoffeeScript 1.6.3
var client;

client = require('./client/client').client;

exports.Client = {
  create: function(config) {
    if (config == null) {
      config = {};
    }
    config.transport || (config.transport = 'https');
    config.hostname || (config.hostname = 'localhost');
    if (config.queueLimit == null) {
      config.queueLimit = 100;
    }
    if (config.rateLimit == null) {
      config.rateLimit = 10;
    }
    return client(config);
  }
};
