// Generated by CoffeeScript 1.6.3
module.exports = function(config) {
  var basicAuth;
  return basicAuth = {
    type: 'request',
    requestAuth: function(httpRequest) {
      var password, username;
      username = config.authenticator.username;
      password = config.authenticator.password;
      return httpRequest.opts.auth = "" + username + ":" + password;
    }
  };
};
