// Generated by CoffeeScript 1.6.3
module.exports = function(config) {
  var basicAuth;
  return basicAuth = {
    type: 'session',
    originalRequest: void 0,
    failedAuth: function(action) {
      var error;
      error = new Error('dinkum authentication failure (session)');
      try {
        error.detail = basicAuth.originalRequest.opts;
      } catch (_error) {}
      basicAuth.originalRequest.promised.reject(error);
      basicAuth.originalRequest = void 0;
      return action.reject();
    },
    sessionAuth: function(action, forbiddenRequest) {
      var authRequest;
      if (forbiddenRequest.authenticator === 'basic_auth') {
        basicAuth.failedAuth(action);
        return;
      }
      basicAuth.originalRequest = forbiddenRequest;
      authRequest = forbiddenRequest;
      authRequest.authenticator = 'basic_auth';
      return action.resolve(authRequest);
    }
  };
};
