// Generated by CoffeeScript 1.6.3
module.exports = function(config) {
  var basicAuth;
  return basicAuth = {
    type: 'session',
    originalRequest: void 0,
    failedAuth: function(action) {
      basicAuth.originalRequest.reject(new Error('Authentication Failed'));
      basicAuth.originalRequest = void 0;
      return action.reject();
    },
    startAuth: function(action, forbiddenRequest) {
      var authRequest;
      if (forbiddenRequest.authenticator === 'basic_auth') {
        basicAuth.failedAuth(action);
        return;
      }
      basicAuth.originalRequest = forbiddenRequest;
      authRequest = forbiddenRequest;
      authRequest.authenticator = 'basic_auth';
      return action.resolve(authRequest);
    }
  };
};
